-- MySQL Database Schema for Creoed LMS (XAMPP / phpMyAdmin)

CREATE TABLE IF NOT EXISTS Roles (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RoleName VARCHAR(50) NOT NULL UNIQUE
);

INSERT IGNORE INTO Roles (RoleName) VALUES ('Super Admin'), ('Admin'), ('Tutor'), ('Student');

CREATE TABLE IF NOT EXISTS Users (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Phone VARCHAR(20),
    PasswordHash VARCHAR(255) NOT NULL,
    RoleID INT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RoleID) REFERENCES Roles(ID)
);

CREATE TABLE IF NOT EXISTS Courses (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(150) NOT NULL,
    Description TEXT,
    TotalFee DECIMAL(10, 2) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Classes (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CourseID INT NOT NULL,
    TutorID INT NOT NULL,
    BatchName VARCHAR(100) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CourseID) REFERENCES Courses(ID),
    FOREIGN KEY (TutorID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS ClassStudents (
    ClassID INT NOT NULL,
    StudentID INT NOT NULL,
    AssignedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ClassID, StudentID),
    FOREIGN KEY (ClassID) REFERENCES Classes(ID),
    FOREIGN KEY (StudentID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Modules (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ClassID INT NOT NULL,
    Title VARCHAR(150) NOT NULL,
    Description TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClassID) REFERENCES Classes(ID)
);

CREATE TABLE IF NOT EXISTS Lessons (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ModuleID INT NOT NULL,
    Title VARCHAR(150) NOT NULL,
    Type VARCHAR(50) NOT NULL, -- 'Video', 'Document', 'Link'
    ContentUrl VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ModuleID) REFERENCES Modules(ID)
);

CREATE TABLE IF NOT EXISTS Assignments (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ModuleID INT NOT NULL,
    Title VARCHAR(150) NOT NULL,
    Description TEXT,
    DueDate DATETIME,
    AttachmentInstructions TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ModuleID) REFERENCES Modules(ID)
);

CREATE TABLE IF NOT EXISTS Submissions (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AssignmentID INT NOT NULL,
    StudentID INT NOT NULL,
    FileUrl VARCHAR(255) NOT NULL,
    Grade DECIMAL(5, 2),
    Feedback TEXT,
    SubmittedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AssignmentID) REFERENCES Assignments(ID),
    FOREIGN KEY (StudentID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Sessions (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ClassID INT NOT NULL,
    Title VARCHAR(150) NOT NULL,
    SessionDate DATE NOT NULL,
    SessionTime TIME NOT NULL,
    MeetingLink VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClassID) REFERENCES Classes(ID)
);

CREATE TABLE IF NOT EXISTS Attendance (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SessionID INT NOT NULL,
    StudentID INT NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Present', -- 'Present', 'Absent'
    RecordedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES Sessions(ID),
    FOREIGN KEY (StudentID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Tickets (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    StudentID INT NOT NULL,
    TutorID INT,
    Subject VARCHAR(150) NOT NULL,
    Description TEXT NOT NULL,
    AttachmentUrl VARCHAR(255),
    Status VARCHAR(20) NOT NULL DEFAULT 'Open', -- 'Open', 'In Progress', 'Resolved'
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentID) REFERENCES Users(ID),
    FOREIGN KEY (TutorID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS TicketReplies (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TicketID INT NOT NULL,
    UserID INT NOT NULL,
    Message TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TicketID) REFERENCES Tickets(ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Announcements (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    TargetType VARCHAR(20) NOT NULL, -- 'All', 'Class'
    TargetClassID INT,
    Title VARCHAR(150) NOT NULL,
    Message TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (TargetClassID) REFERENCES Classes(ID)
);

CREATE TABLE IF NOT EXISTS FeeManagement (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    StudentID INT NOT NULL,
    CourseID INT NOT NULL,
    TotalFee DECIMAL(10, 2) NOT NULL,
    AmountPaid DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    PaymentStatus VARCHAR(20) NOT NULL DEFAULT 'Pending', -- 'Paid', 'Partial', 'Pending'
    LastUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (StudentID) REFERENCES Users(ID),
    FOREIGN KEY (CourseID) REFERENCES Courses(ID)
);
